name = "app-wallet-integration"
main = "src/frontend/index.ts"
compatibility_date = "2024-01-01"

[vars]
BACKEND_URL = "http://localhost:4444"
ALLOWED_ORIGIN = "*"
TARGET_IFRAME_URL = "http://localhost:3000"
