name = "api-wallet-integration"
main = "src/backend/index.ts"
compatibility_date = "2024-01-01"

[vars]
TARGET_API_URL = "http://localhost:4000"
ALLOWED_ORIGIN = "*"
COOKIE_NAME = "api_access_token"
PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAED+H2r3IO2bBH3piHvxftljelW5uA\nthFZ/gDQ4F408uKqZyRe9DMXpAQ0+x9TW7qO9xgSXTmKcvzm2dQsh1sOCw==\n-----END PUBLIC KEY-----\n"
